config/routes.rb
GuestbookApp::Application.routes.draw do
  resources :reviews, only: [:index, :new, :create]
  
  root "reviews#index"

  

end

app/models/review.rb
class Review < ActiveRecord::Base
  default_scope -> { order('created_at DESC') }
  validates :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end
  
  def new
    @review = Review.new
  end
  
  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to root_url
    else
      render 'reviews/new'
    end
  end
  
  private

    def review_params
      params.require(:review).permit(:text, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GuestbookApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reviews/index.html.erb
<h1>Reviews</h1>

<% @reviews.each do |review| %>
<p>
  <%= review.text %>
  <br>
  <% if !review.author.blank? %>
    by <%= review.author %>
    <br>
  <% end %>
  Posted <%= time_ago_in_words(review.created_at) %> ago.
<% end %>
  
  <h2><%= link_to "New review", new_review_path %></h2>
  

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= form_for(@review, action: '/reviews/index', method: 'post') do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :text, placeholder: "Review..." %>
  </div>
  <div class="field">
    <%= f.text_field :author, placeholder: "Author..." %>      
  </div>
  <%= f.submit "Post review" %>
<% end %>

<p>
  <%= link_to "Back", root_url %>

app/views/shared/_error_messages.html.erb
<% if @review.errors.any? %>
  <div id="error_explanation">
    <div class="alert">
      The form contains <%= pluralize(@review.errors.count, "error") %>.
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>